fix(dependencies): upgraded dependencies to fix 3rd party vulnerability
rcruzper/express-actuator pull request #64
Opened 2022-05-08 04:52 UTC by tchopra91

[CVE-2022-24785](https://github.com/advisories/GHSA-8hfj-j24r-96c4) - High Severity Vulnerability
 Vulnerable Library - moment-2.29.1.tgz
Parse, validate, manipulate, and display dates

Library home page: https://registry.npmjs.org/moment/-/moment-2.29.1.tgz

Path to dependency file: /package.json

Path to vulnerable library: /node_modules/moment/package.json

Dependency Hierarchy:

express-actuator-1.8.0.tgz (Root Library)
❌ moment-2.29.1.tgz (Vulnerable Library)
Found in base branch: master

 Vulnerability Details
Moment.js is a JavaScript date library for parsing, validating, manipulating, and formatting dates. A path traversal vulnerability impacts npm (server) users of Moment.js between versions 1.0.1 and 2.29.1, especially if a user-provided locale string is directly used to switch moment locale. This problem is patched in 2.29.2, and the patch can be applied to all affected versions. As a workaround, sanitize the user-provided locale name before passing it to Moment.js.

Publish Date: 2022-04-04

URL: [CVE-2022-24785](https://vuln.whitesourcesoftware.com/vulnerability/CVE-2022-24785)

 CVSS 3 Score Details (7.5)
Base Score Metrics:

Exploitability Metrics:
Attack Vector: Network
Attack Complexity: Low
Privileges Required: None
User Interaction: None
Scope: Unchanged
Impact Metrics:
Confidentiality Impact: None
Integrity Impact: High
Availability Impact: None
For more information on CVSS3 Scores, click [here](https://www.first.org/cvss/calculator/3.0).
 Suggested Fix
Type: Upgrade version

Origin: [GHSA-8hfj-j24r-96c4](https://github.com/moment/moment/security/advisories/GHSA-8hfj-j24r-96c4)

Release Date: 2022-04-04

Fix Resolution: moment - 2.29.2,Moment.js - 2.29.2

2022-05-16 10:32 UTC, rcruzper requested changes
You shouldn't delete package-lock.json. As you can see here: https://docs.npmjs.com/cli/v8/configuring-npm/package-lock-json

```
This file is intended to be committed into source repositories, and serves various purposes:

Describe a single representation of a dependency tree such that teammates, deployments, and continuous integration are guaranteed to install exactly the same dependencies.

Provide a facility for users to "time-travel" to previous states of node_modules without having to commit the directory itself.

Facilitate greater visibility of tree changes through readable source control diffs.

Optimize the installation process by allowing npm to skip repeated metadata resolutions for previously-installed packages.

As of npm v7, lockfiles include enough information to gain a complete picture of the package tree, reducing the need to read package.json files, and allowing for significant performance improvements.
```

2022-05-28 06:59 UTC, tchopra91 commented
Sorry for the confusion, looks like I was on an older version of nodejs, which downgraded the package-lock.json file from v2 to v1.

2022-05-28 07:15 UTC, rcruzper commented
> Sorry for the confusion, looks like I was on an older version of nodejs, which downgraded the package-lock.json file from v2 to v1.

no problem, I'd also split the pr in two, one with the dependency update and another one with the refactor

2022-06-06 08:44 UTC, rcruzper commented
moment library has been removed in favor of dayjs.

2022-06-06 08:44 UTC, closed without merging

2022-06-17 04:31 UTC, tchopra91 commented
okz thanks, I will split the changes into two pr.